package com.tigo.utils;

import java.util.ResourceBundle;

public class ParametersWeb
{
  public static String EXPRECION_REGULAR_USUARIO;
  public static String MENSAJE_VALIDACION_USUARIO;
  public static String EXPRECION_REGULAR_PASSWORD;
  public static String MENSAJE_VALIDACION_PASSWORD;
  public static String TEXTO_COMUN;
  public static String MENSAJE_COMUN;
  public static String OPERADOR_RELACIONAL;
  public static String EXPRESION_REGULAR_TODO;
  public static String EXPRESION_REGULAR_TODO_NO_ESP;
  public static String EXPRESION_REGULAR_NUMERO;
  public static String ER_LISTA_USUARIOS;
  public static String EXPRESION_REGULAR_NUMEROC;
  public static String EXPRESION_REGULAR_COMPROBANTE;
  public static String ER_LISTA_COMPROBANTES;
  public static String EXPRESION_REGULAR_SERIE;
  public static String EXPRESION_REGULAR_ODECO;
  public static String EXPRESION_REGULAR_ICCID;
  
  public static String WS_PORTABILIDAD_DELETE_BCCS;
  public static String WS_PORTABILIDAD_DELETE_BCCS_SLEEP;
  public static String WS_PORTABILIDAD_DELETE_BCCS_ACTIVE;
  public static String WS_PORTABILIDAD_DELETE_BCCS_REQUEST;
  
  public static String WS_PORTABILIDAD_DELETE_SVA;
  public static String WS_PORTABILIDAD_DELETE_SVA_SLEEP;
  public static String WS_PORTABILIDAD_DELETE_SVA_ACTIVE;
  public static String WS_PORTABILIDAD_DELETE_SVA_REQUEST;
  
  public static String WS_PORTABILIDAD_QUITAR_CUENTA;
  public static String WS_PORTABILIDAD_QUITAR_CUENTA_SLEEP;
  public static String WS_PORTABILIDAD_QUITAR_CUENTA_ACTIVE;
  public static String WS_PORTABILIDAD_QUITAR_CUENTA_REQUEST;
  
  public static String WS_PORTABILIDAD_OBTENER_CUENTAS;
  public static String WS_PORTABILIDAD_OBTENER_CUENTAS_SLEEP;
  public static String WS_PORTABILIDAD_OBTENER_CUENTAS_ACTIVE;
  public static String WS_PORTABILIDAD_OBTENER_CUENTAS_REQUEST;
  
  static
  {
    try
    {
    	init();
    }
    catch (Exception e)
    {
      e.printStackTrace();
    }
  }
  
  public static void init()
  {
    String configFile = "config_web_es";
    ResourceBundle rb = ResourceBundle.getBundle(configFile);
    
    EXPRECION_REGULAR_USUARIO = rb.getString("EXPRECION_REGULAR_USUARIO");
    MENSAJE_VALIDACION_USUARIO = rb.getString("MENSAJE_VALIDACION_USUARIO");
    EXPRECION_REGULAR_PASSWORD = rb.getString("EXPRECION_REGULAR_PASSWORD");
    MENSAJE_VALIDACION_PASSWORD = rb.getString("MENSAJE_VALIDACION_PASSWORD");
    TEXTO_COMUN = rb.getString("TEXTO_COMUN");
    MENSAJE_COMUN = rb.getString("MENSAJE_COMUN");
    OPERADOR_RELACIONAL = rb.getString("OPERADOR_RELACIONAL");
    
    EXPRESION_REGULAR_TODO = rb.getString("EXPRESION_REGULAR_TODO");
    EXPRESION_REGULAR_TODO_NO_ESP = rb.getString("EXPRESION_REGULAR_TODO_NO_ESP");
    EXPRESION_REGULAR_NUMERO = rb.getString("EXPRESION_REGULAR_NUMERO");
    ER_LISTA_USUARIOS=rb.getString("ER_LISTA_USUARIOS");
    
    EXPRESION_REGULAR_NUMEROC = rb.getString("EXPRESION_REGULAR_NUMEROC");
    EXPRESION_REGULAR_COMPROBANTE = rb.getString("EXPRESION_REGULAR_COMPROBANTE");
    EXPRESION_REGULAR_SERIE = rb.getString("EXPRESION_REGULAR_SERIE");
    
    ER_LISTA_COMPROBANTES=rb.getString("ER_LISTA_COMPROBANTES");
    EXPRESION_REGULAR_ODECO=rb.getString("EXPRESION_REGULAR_ODECO");
    EXPRESION_REGULAR_ICCID=rb.getString("EXPRESION_REGULAR_ICCID");
    
    WS_PORTABILIDAD_DELETE_BCCS=rb.getString("WS_PORTABILIDAD_DELETE_BCCS");
    WS_PORTABILIDAD_DELETE_BCCS_SLEEP=rb.getString("WS_PORTABILIDAD_DELETE_BCCS_SLEEP");
    WS_PORTABILIDAD_DELETE_BCCS_ACTIVE=rb.getString("WS_PORTABILIDAD_DELETE_BCCS_ACTIVE");
    WS_PORTABILIDAD_DELETE_BCCS_REQUEST=rb.getString("WS_PORTABILIDAD_DELETE_BCCS_REQUEST");
    
    WS_PORTABILIDAD_DELETE_SVA=rb.getString("WS_PORTABILIDAD_DELETE_SVA");
    WS_PORTABILIDAD_DELETE_SVA_SLEEP=rb.getString("WS_PORTABILIDAD_DELETE_SVA_SLEEP");
    WS_PORTABILIDAD_DELETE_SVA_ACTIVE=rb.getString("WS_PORTABILIDAD_DELETE_SVA_ACTIVE");
    WS_PORTABILIDAD_DELETE_SVA_REQUEST=rb.getString("WS_PORTABILIDAD_DELETE_SVA_REQUEST");
    
    WS_PORTABILIDAD_QUITAR_CUENTA=rb.getString("WS_PORTABILIDAD_QUITAR_CUENTA");
    WS_PORTABILIDAD_QUITAR_CUENTA_SLEEP=rb.getString("WS_PORTABILIDAD_QUITAR_CUENTA_SLEEP");
    WS_PORTABILIDAD_QUITAR_CUENTA_ACTIVE=rb.getString("WS_PORTABILIDAD_QUITAR_CUENTA_ACTIVE");
    WS_PORTABILIDAD_QUITAR_CUENTA_REQUEST=rb.getString("WS_PORTABILIDAD_QUITAR_CUENTA_REQUEST");
    
    WS_PORTABILIDAD_OBTENER_CUENTAS= rb.getString("WS_PORTABILIDAD_OBTENER_CUENTAS");
    WS_PORTABILIDAD_OBTENER_CUENTAS_SLEEP= rb.getString("WS_PORTABILIDAD_OBTENER_CUENTAS_SLEEP");
    WS_PORTABILIDAD_OBTENER_CUENTAS_ACTIVE= rb.getString("WS_PORTABILIDAD_OBTENER_CUENTAS_ACTIVE");
    WS_PORTABILIDAD_OBTENER_CUENTAS_REQUEST= rb.getString("WS_PORTABILIDAD_OBTENER_CUENTAS_REQUEST");
  }
}
